repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      language_version: python3.10

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort
      language_version: python3.10

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
    - id: fix-byte-order-marker
    - id: end-of-file-fixer
    - id: trailing-whitespace
